### PR TITLE
Multiple Filters

### PR DESCRIPTION
**Pull request by asopromadze**
### Changes
- Added functionality to apply multiple filters simultaneously, allowing users to refine their search results more granitely.
- Transitioned data retrieval and filtering processes to the server side using  [tRPC](https://trpc.io/). This update significantly enhances data processing efficiency and reduces the client-side workload.

https://github.com/lucavallin/verto/assets/61462002/fbb6e54f-427e-48af-ab1d-aa390d62b496

The addition of multiple filters significantly improves the user's ability to find relevant results quickly
By handling data retrieval and filtering on the server side, i've lightened the client-side load

**For deployment, ensure the NEXT_PUBLIC_API_URL environment variable is configured**
it's `http://localhost:3000/api/trpc/` for local development

fix https://github.com/lucavallin/verto/issues/212
fix https://github.com/lucavallin/verto/issues/284

#### Page speed result
image

### CODE REVIEW

**Comment by asopromadze** [comment]
@lucavallin  cant assign reviewer or link [isseue](https://github.com/lucavallin/verto/issues/212)

**Comment by asopromadze** [comment]
@lucavallin  
At first glance there no much load for frontend side.
Its only 660 repositories so client side can iterate through it without any delay,  but if repos grows 6k or 60k or etc.  it will be much more delay.
I mean filtering / sorting heppening at `AppDataContext`.
i forgot to mention at pr description
- added icons. used  [devicon](https://devicon.dev/)
image
- every time some some filter / sort criteria changes it appears at query,  so at page refresh it persist
`?languages=ruby&tags=java&search=react&sort=New+Issues`
-  infinity scroll(pagination) happening at server side too

**Comment by asopromadze** [comment]
@lucavallin  
#### For deployment, ensure the NEXT_PUBLIC_API_URL environment variable is configured
image

f.e  for this branch deploy it will be `https://verto-git-fork-asopromadze-asopromadze-multip-a58f0d-lucavallin.vercel.app/api/trpc`,
its now requesting `http://localhost:3000/api/trpc/`  and have error
image

**Comment by lucavallin** [comment]
Thanks @asopromadze ! For the URL, since the app is running on Vercel, it might be easier to use `VERCEL_URL` and `NEXT_PUBLIC_VERCEL_URL` in the code. Those are already set to the correct value (urls of preview branches are unpredictable).

**Comment by asopromadze** [comment]
> Thanks @asopromadze ! For the URL, since the app is running on Vercel, it might be easier to use `VERCEL_URL` and `NEXT_PUBLIC_VERCEL_URL` in the code. Those are already set to the correct value (urls of preview branches are unpredictable).
Ok, I will change it

**Comment by asopromadze** [comment]
@lucavallin i have used vercel system env variables as you suggest.
`NEXT_PUBLIC_VERCEL_URL` and  `NEXT_PUBLIC_VERCEL_BRANCH_URL` 
can you trigger this pr deploy to check if its correct ?

**Comment by lucavallin** [comment]
Hey @asopromadze! It's deploying nicely, but there are some configuration issues in the console (data is not loading):

image

**Comment by asopromadze** [comment]
> Hey @asopromadze! It's deploying nicely, but there are some configuration issues in the console (data is not loading):
> 
> image

Ok,  i ll fix it

**Review by lucavallin — APPROVED** [review]
Awesome, thanks a lot! Let's see if the problem is gone if we merge it

**Comment by lucavallin** [comment]
Screenshot 2024-04-08 at 21 07 44

Nope, it doesn't seem to work in production either. My guess is that some extra permissions/config is missing in `next.config.js` @asopromadze

**Comment by asopromadze** [comment]
its requesting
[this deploy](https://verto-git-main-lucavallins-projects.vercel.app/)
and have cors error
we have two options 
- add trusted origin it prod deploy
- or add https://www.verto.sh/  this env as backend api url

**Comment by asopromadze** [comment]
image

**Comment by asopromadze** [comment]
Is prod deployed at vercel ?

**Comment by asopromadze** [comment]
https://github.com/vercel/next.js/discussions/16429#discussioncomment-1302156

**Comment by asopromadze** [comment]
I ll try fix this

**Pull request merged**
