### PR TITLE
Fix trpc route path

### PR DESCRIPTION
**Pull request by asopromadze**
- api route path for prod deploy
image

### CODE REVIEW

**Comment by asopromadze** [comment]
@lucavallin  Can you try once more trigger deploy ? Thanks

**Review by lucavallin — APPROVED** [review]
Let's try again!

**Comment by lucavallin** [comment]
Yep, this works now, thanks! I merged it and the changes are live.
The API for preview deployments however is still broken (it always goes to `verto.sh`). Do you mind checking that to see what we need to do to fix it? Thanks!

**Comment by asopromadze** [comment]
> Yep, this works now, thanks! I merged it and the changes are live.
> The API for preview deployments however is still broken (it always goes to `verto.sh`). Do you mind checking that to see what we need to do to fix it? Thanks!
> 
> A few bugs I found:
> - It seems we are not updating the page title anymore, which might be bad for SEO.
> - Filters are not reset when going back to the homepage
> 
> I am going to revert the PR. It works, but we need to fix these issues first :) 

Thanka. ill try fix main issue,
Another two bug is easy to fix

**Pull request merged**
